### ISSUE TITLE
非粘性是如何实现的?

### ISSUE THREAD

**Issue by zuilintan** [BugRui/LiveDataBus#1]
与网上其他LiveDataBus对比, 
似乎只有LiveDataBusManager的实例是volatile修饰有所差异, 
关键在此吗?

**Comment by BugRui** [comment]
不是的，只是单例模式中用volatile和synchronized来满足双重检查锁机制

**Comment by BugRui** [comment]
使用liveData实现非粘性的关键之处在于 with，每次 with都会重新new MutableLiveData<>()，避免了收到重复的消息，比如当页面发生旋转，send时通过tag找到对应的MutableLiveData进行发送，与网上其他LiveDataBus对比，就是保持LiveData的原汁原味，不需要反射，不需要修改LiveData的源码

**Comment by BugRui** [comment]
因为公司项目需要使用类似EventBus 的消息事件功能，不想引入EventBus ，网上其他LiveDataBus对LiveData改动过大，所以自己写了LiveDataBus，如果使用出现问题，可及时反馈，我看到会进行修复

**Comment by zuilintan** [comment]
感谢, 很详细

**Comment by zuilintan** [comment]
如果要在此基础上使用粘性该怎么做呢?

**Comment by BugRui** [comment]
更新了1.1.0版本，新加了粘性的支持，你可以看看

**Comment by zuilintan** [comment]
1.1.0满足了我的需求, 感谢
