### ISSUE TITLE
有一点小疑问

### ISSUE THREAD

**Issue by hurist** [BugRui/LiveDataBus#2]
我看到每次订阅一个事件的时候都是重新new的一个MutableLiveData，如果我多个地方都订阅这个事件的话，就只有最后订阅的那个才能收到吗？

**Comment by BugRui** [comment]
不同的事件使用不同的tag做区分

**Comment by hurist** [comment]
> 不同的事件使用不同的tag做区分

就是多处都订阅了某个tag的事件情况

**Comment by BugRui** [comment]
没有做这个实现，因为暂时想到的方法是添加一个特殊的tag区分，比如LifecycleOwner换成当前activity，获取这个activity的包路径和activity名称做为一个特殊的tag区分，暂时没有更好的方案，想到会加进去。
